export const ChatIcons: any = [
{Filename: '128.png', FilePath: '../../assets/imgs/chat/faces/128.png', FileGroup: 'Faces', Description: 'Enchanted', FileSize: 32},
{Filename: '128-1.png', FilePath: '../../assets/imgs/chat/faces/128-1.png', FileGroup: 'Faces', Description: 'Cool', FileSize: 32},
{Filename: '128-2.png', FilePath: '../../assets/imgs/chat/faces/128-2.png', FileGroup: 'Faces', Description: 'Amazing', FileSize: 32},
{Filename: '128-3.png', FilePath: '../../assets/imgs/chat/faces/128-3.png', FileGroup: 'Faces', Description: 'Feling Bad', FileSize: 32},
{Filename: '128-4.png', FilePath: '../../assets/imgs/chat/faces/128-4.png', FileGroup: 'Faces', Description: 'Displeased', FileSize: 32},
{Filename: '128-5.png', FilePath: '../../assets/imgs/chat/faces/128-5.png', FileGroup: 'Faces', Description: 'Feeling Mad Too', FileSize: 32},
{Filename: '128-6.png', FilePath: '../../assets/imgs/chat/faces/128-6.png', FileGroup: 'Faces', Description: 'Scared', FileSize: 32},
{Filename: '128-7.png', FilePath: '../../assets/imgs/chat/faces/128-7.png', FileGroup: 'Faces', Description: 'Dont Care', FileSize: 32},
{Filename: '128-9.png', FilePath: '../../assets/imgs/chat/faces/128-9.png', FileGroup: 'Faces', Description: 'Shouting Mad', FileSize: 32},
{Filename: '128-11.png', FilePath: '../../assets/imgs/chat/faces/128-11.png', FileGroup: 'Faces', Description: 'Feeling Guilty', FileSize: 32},
{Filename: '128-12.png', FilePath: '../../assets/imgs/chat/faces/128-12.png', FileGroup: 'Faces', Description: 'In Love', FileSize: 32},
{Filename: '128-13.png', FilePath: '../../assets/imgs/chat/faces/128-13.png', FileGroup: 'Faces', Description: 'Happy Tong', FileSize: 32},
{Filename: '128-14.png', FilePath: '../../assets/imgs/chat/faces/128-14.png', FileGroup: 'Faces', Description: 'Scared Tong', FileSize: 32},
{Filename: '128-15.png', FilePath: '../../assets/imgs/chat/faces/128-15.png', FileGroup: 'Faces', Description: 'Mad Tong', FileSize: 32},
{Filename: '128-16.png', FilePath: '../../assets/imgs/chat/faces/128-16.png', FileGroup: 'Faces', Description: 'Lovely Kiss', FileSize: 32},
{Filename: '128-17.png', FilePath: '../../assets/imgs/chat/faces/128-17.png', FileGroup: 'Faces', Description: 'Wink', FileSize: 32},
{Filename: '128-18.png', FilePath: '../../assets/imgs/chat/faces/128-18.png', FileGroup: 'Faces', Description: 'Laughing Out Loud', FileSize: 32},
{Filename: '128-19.png', FilePath: '../../assets/imgs/chat/faces/128-19.png', FileGroup: 'Faces', Description: 'Crazy Laugh', FileSize: 32},
{Filename: '128-20.png', FilePath: '../../assets/imgs/chat/faces/128-20.png', FileGroup: 'Faces', Description: 'Big Smile', FileSize: 32},
{Filename: '128-21.png', FilePath: '../../assets/imgs/chat/faces/128-21.png', FileGroup: 'Faces', Description: 'Smirking', FileSize: 32},
{Filename: '128-22.png', FilePath: '../../assets/imgs/chat/faces/128-22.png', FileGroup: 'Faces', Description: 'Question', FileSize: 32},
{Filename: '128-23.png', FilePath: '../../assets/imgs/chat/faces/128-23.png', FileGroup: 'Faces', Description: 'Feeling Sleapy', FileSize: 32},
{Filename: '128-24.png', FilePath: '../../assets/imgs/chat/faces/128-24.png', FileGroup: 'Faces', Description: 'Surprised', FileSize: 32},
{Filename: '128-25.png', FilePath: '../../assets/imgs/chat/faces/128-25.png', FileGroup: 'Faces', Description: 'Smile', FileSize: 32},
{Filename: '128-26.png', FilePath: '../../assets/imgs/chat/faces/128-26.png', FileGroup: 'Faces', Description: 'Dont Care', FileSize: 32},
{Filename: '128-27.png', FilePath: '../../assets/imgs/chat/faces/128-27.png', FileGroup: 'Faces', Description: 'Sarcastic Laugh', FileSize: 32},
{Filename: '128-28.png', FilePath: '../../assets/imgs/chat/faces/128-28.png', FileGroup: 'Faces', Description: 'Crazy Laugh', FileSize: 32},
{Filename: '128-29.png', FilePath: '../../assets/imgs/chat/faces/128-29.png', FileGroup: 'Faces', Description: 'Crying', FileSize: 32},
{Filename: '128-30.png', FilePath: '../../assets/imgs/chat/faces/128-30.png', FileGroup: 'Faces', Description: 'Oh', FileSize: 32},
{Filename: '128-31.png', FilePath: '../../assets/imgs/chat/faces/128-31.png', FileGroup: 'Faces', Description: 'I Am Sad', FileSize: 32},
{Filename: '128-33.png', FilePath: '../../assets/imgs/chat/faces/128-33.png', FileGroup: 'Faces', Description: 'I Am Mad', FileSize: 32},
{Filename: '128-34.png', FilePath: '../../assets/imgs/chat/faces/128-34.png', FileGroup: 'Faces', Description: 'Crazy Surprise', FileSize: 32},
{Filename: '128-35.png', FilePath: '../../assets/imgs/chat/faces/128-35.png', FileGroup: 'Faces', Description: 'Very Surpised', FileSize: 32},
{Filename: '128-36.png', FilePath: '../../assets/imgs/chat/faces/128-36.png', FileGroup: 'Faces', Description: 'Smile Too', FileSize: 32},
{Filename: '128-37.png', FilePath: '../../assets/imgs/chat/faces/128-37.png', FileGroup: 'Faces', Description: 'Smiling', FileSize: 32},
{Filename: '128-38.png', FilePath: '../../assets/imgs/chat/faces/128-38.png', FileGroup: 'Faces', Description: 'Happily In Love', FileSize: 32},
{Filename: '128-39.png', FilePath: '../../assets/imgs/chat/faces/128-39.png', FileGroup: 'Faces', Description: 'Laughing', FileSize: 32},
{Filename: 'angel.png', FilePath: '../../assets/imgs/chat/faces2/angel.png', FileGroup: 'Faces2', Description: 'Angel', FileSize: 32},
{Filename: 'angry.png', FilePath: '../../assets/imgs/chat/faces2/angry.png', FileGroup: 'Faces2', Description: 'Angry', FileSize: 32},
{Filename: 'clown.png', FilePath: '../../assets/imgs/chat/faces2/clown.png', FileGroup: 'Faces2', Description: 'Clown', FileSize: 32},
{Filename: 'cool.png', FilePath: '../../assets/imgs/chat/faces2/cool.png', FileGroup: 'Faces2', Description: 'Cool', FileSize: 32},
{Filename: 'crying.png', FilePath: '../../assets/imgs/chat/faces2/crying.png', FileGroup: 'Faces2', Description: 'Crying', FileSize: 32},
{Filename: 'devil.png', FilePath: '../../assets/imgs/chat/faces2/devil.png', FileGroup: 'Faces2', Description: 'Devil', FileSize: 32},
{Filename: 'displeased.png', FilePath: '../../assets/imgs/chat/faces2/displeased.png', FileGroup: 'Faces2', Description: 'Displeased', FileSize: 32},
{Filename: 'happy.png', FilePath: '../../assets/imgs/chat/faces2/happy.png', FileGroup: 'Faces2', Description: 'Happy', FileSize: 32},
{Filename: 'harrypotter.png', FilePath: '../../assets/imgs/chat/faces2/harrypotter.png', FileGroup: 'Faces2', Description: 'Harry Potter', FileSize: 32},
{Filename: 'hypnotize.png', FilePath: '../../assets/imgs/chat/faces2/hypnotize.png', FileGroup: 'Faces2', Description: 'Hypnotize', FileSize: 32},
{Filename: 'hypnotized.png', FilePath: '../../assets/imgs/chat/faces2/hypnotized.png', FileGroup: 'Faces2', Description: 'Hypnotized', FileSize: 32},
{Filename: 'inlove.png', FilePath: '../../assets/imgs/chat/faces2/inlove.png', FileGroup: 'Faces2', Description: 'In Love', FileSize: 32},
{Filename: 'kiss.png', FilePath: '../../assets/imgs/chat/faces2/kiss.png', FileGroup: 'Faces2', Description: 'Kiss', FileSize: 32},
{Filename: 'kissed.png', FilePath: '../../assets/imgs/chat/faces2/kissed.png', FileGroup: 'Faces2', Description: 'Kissed', FileSize: 32},
{Filename: 'laughtingoutloud.png', FilePath: '../../assets/imgs/chat/faces2/laughtingoutloud.png', FileGroup: 'Faces2', Description: 'Laughing Out Loud', FileSize: 32},
{Filename: 'money.png', FilePath: '../../assets/imgs/chat/faces2/money.png', FileGroup: 'Faces2', Description: 'Money', FileSize: 32},
{Filename: 'party.png', FilePath: '../../assets/imgs/chat/faces2/party.png', FileGroup: 'Faces2', Description: 'Lets Party', FileSize: 32},
{Filename: 'pirate.png', FilePath: '../../assets/imgs/chat/faces2/pirate.png', FileGroup: 'Faces2', Description: 'Pirates', FileSize: 32},
{Filename: 'question.png', FilePath: '../../assets/imgs/chat/faces2/question.png', FileGroup: 'Faces2', Description: 'Question', FileSize: 32},
{Filename: 'sad.png', FilePath: '../../assets/imgs/chat/faces2/sad.png', FileGroup: 'Faces2', Description: 'Sad', FileSize: 32},
{Filename: 'sleeping.png', FilePath: '../../assets/imgs/chat/faces2/sleeping.png', FileGroup: 'Faces2', Description: 'Sleaping', FileSize: 32},
{Filename: 'surprised.png', FilePath: '../../assets/imgs/chat/faces2/surprised.png', FileGroup: 'Faces2', Description: 'Surprised', FileSize: 32},
{Filename: 'terminator.png', FilePath: '../../assets/imgs/chat/faces2/terminator.png', FileGroup: 'Faces2', Description: 'Terminator', FileSize: 32},
{Filename: 'tongue.png', FilePath: '../../assets/imgs/chat/faces2/tongue.png', FileGroup: 'Faces2', Description: 'Tongue', FileSize: 32},
{Filename: 'vomited.png', FilePath: '../../assets/imgs/chat/faces2/vomited.png', FileGroup: 'Faces2', Description: 'Feeling Sick', FileSize: 32},
{Filename: 'watermelon.png', FilePath: '../../assets/imgs/chat/faces2/watermelon.png', FileGroup: 'Faces2', Description: 'Watermelon', FileSize: 32},
{Filename: 'wink.png', FilePath: '../../assets/imgs/chat/faces2/wink.png', FileGroup: 'Faces2', Description: 'Wink', FileSize: 32},
{Filename: 'Actor_Female_Light.png', FilePath: '../../assets/imgs/chat/people/Actor_Female_Light.png', FileGroup: 'People', Description: 'Actor Female', FileSize: 32},
{Filename: 'Actor_Male_Dark.png', FilePath: '../../assets/imgs/chat/people/Actor_Male_Dark.png', FileGroup: 'People', Description: 'Actor Male Dark', FileSize: 32},
{Filename: 'Actor_Male_Light.png', FilePath: '../../assets/imgs/chat/people/Actor_Male_Light.png', FileGroup: 'People', Description: 'Actor Male Light', FileSize: 32},
{Filename: 'free_for_job.png', FilePath: '../../assets/imgs/chat/people/free_for_job.png', FileGroup: 'People', Description: 'Free For Job', FileSize: 32},
{Filename: 'Group_Meeting_Dark.png', FilePath: '../../assets/imgs/chat/people/Group_Meeting_Dark.png', FileGroup: 'People', Description: 'Group Meeting Dark', FileSize: 32},
{Filename: 'Group_Meeting_Light.png', FilePath: '../../assets/imgs/chat/people/Group_Meeting_Light.png', FileGroup: 'People', Description: 'Group Meeting Light', FileSize: 32},
{Filename: 'P_Admin.png', FilePath: '../../assets/imgs/chat/people/P_Admin.png', FileGroup: 'People', Description: 'Administrator', FileSize: 32},
{Filename: 'P_Angel.png', FilePath: '../../assets/imgs/chat/people/P_Angel.png', FileGroup: 'People', Description: 'Angel', FileSize: 32},
{Filename: 'P_Devil.png', FilePath: '../../assets/imgs/chat/people/P_Devil.png', FileGroup: 'People', Description: 'Devil', FileSize: 32},
{Filename: 'P_Army_officer.png', FilePath: '../../assets/imgs/chat/people/P_Army_officer.png', FileGroup: 'People', Description: 'Army Officer', FileSize: 32},
{Filename: 'P_Asian_boss.png', FilePath: '../../assets/imgs/chat/people/P_Asian_boss.png', FileGroup: 'People', Description: 'Asian', FileSize: 32},
{Filename: 'P_Businessman.png', FilePath: '../../assets/imgs/chat/people/P_Businessman.png', FileGroup: 'People', Description: 'Businessman', FileSize: 32},
{Filename: 'P_Captain.png', FilePath: '../../assets/imgs/chat/people/P_Captain.png', FileGroup: 'People', Description: 'Captain', FileSize: 32},
{Filename: 'P_Caucasian_boss.png', FilePath: '../../assets/imgs/chat/people/P_Caucasian_boss.png', FileGroup: 'People', Description: 'Caucasian Man', FileSize: 32},
{Filename: 'P_Caucasian_female_boss.png', FilePath: '../../assets/imgs/chat/people/P_Caucasian_female_boss.png', FileGroup: 'People', Description: 'Caucasian Female', FileSize: 32},
{Filename: 'P_Chief.png', FilePath: '../../assets/imgs/chat/people/P_Chief.png', FileGroup: 'People', Description: 'Chief', FileSize: 32},
{Filename: 'P_Arab_boss.png', FilePath: '../../assets/imgs/chat/people/P_Arab_boss.png', FileGroup: 'People', Description: 'Arab', FileSize: 32},
{Filename: 'P_elvis.png', FilePath: '../../assets/imgs/chat/people/P_elvis.png', FileGroup: 'People', Description: 'Elvis', FileSize: 32},
{Filename: 'P_Engineer.png', FilePath: '../../assets/imgs/chat/people/P_Engineer.png', FileGroup: 'People', Description: 'Engineer', FileSize: 32},
{Filename: 'P_General.png', FilePath: '../../assets/imgs/chat/people/P_General.png', FileGroup: 'People', Description: 'General', FileSize: 32},
{Filename: 'P_Global_manager.png', FilePath: '../../assets/imgs/chat/people/P_Global_manager.png', FileGroup: 'People', Description: 'Global Manager', FileSize: 32},
{Filename: 'P_Head_physician.png', FilePath: '../../assets/imgs/chat/people/P_Head_physician.png', FileGroup: 'People', Description: 'Doctor', FileSize: 32},
{Filename: 'P_holmes.png', FilePath: '../../assets/imgs/chat/people/P_holmes.png', FileGroup: 'People', Description: 'Private Eye', FileSize: 32},
{Filename: 'P_Judge.png', FilePath: '../../assets/imgs/chat/people/P_Judge.png', FileGroup: 'People', Description: 'Judge', FileSize: 32},
{Filename: 'P_King.png', FilePath: '../../assets/imgs/chat/people/P_King.png', FileGroup: 'People', Description: 'King', FileSize: 32},
{Filename: 'P_Queen.png', FilePath: '../../assets/imgs/chat/people/P_Queen.png', FileGroup: 'People', Description: 'Queen', FileSize: 32},
{Filename: 'P_Knight.png', FilePath: '../../assets/imgs/chat/people/P_Knight.png', FileGroup: 'People', Description: 'Knight', FileSize: 32},
{Filename: 'P_Manager.png', FilePath: '../../assets/imgs/chat/people/P_Manager.png', FileGroup: 'People', Description: 'Manager', FileSize: 32},
{Filename: 'P_Mexican_boss.png', FilePath: '../../assets/imgs/chat/people/P_Mexican_boss.png', FileGroup: 'People', Description: 'Mexican', FileSize: 32},
{Filename: 'P_Official.png', FilePath: '../../assets/imgs/chat/people/P_Official.png', FileGroup: 'People', Description: 'Government', FileSize: 32},
{Filename: 'P_Old_boss.png', FilePath: '../../assets/imgs/chat/people/P_Old_boss.png', FileGroup: 'People', Description: 'Professor', FileSize: 32},
{Filename: 'P_Police_officer.png', FilePath: '../../assets/imgs/chat/people/P_Police_officer.png', FileGroup: 'People', Description: 'Police Officer', FileSize: 32},
{Filename: 'P_Policeman.png', FilePath: '../../assets/imgs/chat/people/P_Policeman.png', FileGroup: 'People', Description: 'Police Man', FileSize: 32},
{Filename: 'P_potter.png', FilePath: '../../assets/imgs/chat/people/P_potter.png', FileGroup: 'People', Description: 'Harry Potter', FileSize: 32},
{Filename: 'P_Professor.png', FilePath: '../../assets/imgs/chat/people/P_Professor.png', FileGroup: 'People', Description: 'Albert Einstein', FileSize: 32},
{Filename: 'P_Security.png', FilePath: '../../assets/imgs/chat/people/P_Security.png', FileGroup: 'People', Description: 'CIA', FileSize: 32},
{Filename: 'P_Security_guard.png', FilePath: '../../assets/imgs/chat/people/P_Security_guard.png', FileGroup: 'People', Description: 'Security Guard', FileSize: 32},
{Filename: 'P_Sheikh.png', FilePath: '../../assets/imgs/chat/people/P_Sheikh.png', FileGroup: 'People', Description: 'Sheik', FileSize: 32},
{Filename: 'P_Superman.png', FilePath: '../../assets/imgs/chat/people/P_Superman.png', FileGroup: 'People', Description: 'Superman', FileSize: 32},
{Filename: 'P_Supervisor.png', FilePath: '../../assets/imgs/chat/people/P_Supervisor.png', FileGroup: 'People', Description: 'Supervisor', FileSize: 32},
{Filename: 'P_Teacher.png', FilePath: '../../assets/imgs/chat/people/P_Teacher.png', FileGroup: 'People', Description: 'Teacher', FileSize: 32},
{Filename: 'P_terminator.png', FilePath: '../../assets/imgs/chat/people/P_terminator.png', FileGroup: 'People', Description: 'Terminator', FileSize: 32},
{Filename: 'P_Themis.png', FilePath: '../../assets/imgs/chat/people/P_Themis.png', FileGroup: 'People', Description: 'Themis', FileSize: 32},
{Filename: 'P_Wizard.png', FilePath: '../../assets/imgs/chat/people/P_Wizard.png', FileGroup: 'People', Description: 'Wizzard', FileSize: 32},
{Filename: 'santa.png', FilePath: '../../assets/imgs/chat/people/santa.png', FileGroup: 'People', Description: 'Santa', FileSize: 32},
{Filename: 'user5.png', FilePath: '../../assets/imgs/chat/people/user5.png', FileGroup: 'People', Description: 'Male Graduated', FileSize: 32},
{Filename: 'user6.png', FilePath: '../../assets/imgs/chat/people/user6.png', FileGroup: 'People', Description: 'Female Graduated', FileSize: 32},
{Filename: 'x_aion_templar.png', FilePath: '../../assets/imgs/chat/people/x_aion_templar.png', FileGroup: 'People', Description: 'Templar', FileSize: 32},
{Filename: 'x_assasins_creed_2.png', FilePath: '../../assets/imgs/chat/people/x_assasins_creed_2.png', FileGroup: 'People', Description: 'Assassin', FileSize: 32},
{Filename: 'x_guitar_hero_3_a.png', FilePath: '../../assets/imgs/chat/people/x_guitar_hero_3_a.png', FileGroup: 'People', Description: 'Female Guitarist', FileSize: 32},
{Filename: 'x_guitar_hero_3_b.png', FilePath: '../../assets/imgs/chat/people/x_guitar_hero_3_b.png', FileGroup: 'People', Description: 'Male Guitarist', FileSize: 32},
{Filename: 'x_heavenly_sword.png', FilePath: '../../assets/imgs/chat/people/x_heavenly_sword.png', FileGroup: 'People', Description: 'Heroine', FileSize: 32},
{Filename: 'x_iron_man.png', FilePath: '../../assets/imgs/chat/people/x_iron_man.png', FileGroup: 'People', Description: 'Iron Man', FileSize: 32},
{Filename: 'x_sacred_2.png', FilePath: '../../assets/imgs/chat/people/x_sacred_2.png', FileGroup: 'People', Description: 'Mistery', FileSize: 32},
{Filename: 'x_spartan.png', FilePath: '../../assets/imgs/chat/people/x_spartan.png', FileGroup: 'People', Description: 'Spartan', FileSize: 32},
{Filename: 'x_star_wars_battlefront.png', FilePath: '../../assets/imgs/chat/people/x_star_wars_battlefront.png', FileGroup: 'People', Description: 'Star Wars', FileSize: 32},
{Filename: 'x_tabula_rasa.png', FilePath: '../../assets/imgs/chat/people/x_tabula_rasa.png', FileGroup: 'People', Description: 'Female Fighter', FileSize: 32},
{Filename: 'x_timeshift.png', FilePath: '../../assets/imgs/chat/people/x_timeshift.png', FileGroup: 'People', Description: 'Time Shifter', FileSize: 32},
{Filename: 'x_titan_quest.png', FilePath: '../../assets/imgs/chat/people/x_titan_quest.png', FileGroup: 'People', Description: 'Titan Hero', FileSize: 32},
{Filename: 'P_terminator.png', FilePath: '../../assets/imgs/chat/people/P_terminator.png', FileGroup: 'People', Description: 'Terminator', FileSize: 32},
{Filename: 'x_wow_goblin.png', FilePath: '../../assets/imgs/chat/people/x_wow_goblin.png', FileGroup: 'People', Description: 'Gobiln', FileSize: 32},
{Filename: 'Butterfly.png', FilePath: '../../assets/imgs/chat/animals/Butterfly.png', FileGroup: 'Animals', Description: 'Butterfly', FileSize: 32},
{Filename: 'Dolphin.png', FilePath: '../../assets/imgs/chat/animals/Dolphin.png', FileGroup: 'Animals', Description: 'Dolphin', FileSize: 32},
{Filename: 'Elephant.png', FilePath: '../../assets/imgs/chat/animals/Elephant.png', FileGroup: 'Animals', Description: 'Elephant', FileSize: 32},
{Filename: 'Panda.png', FilePath: '../../assets/imgs/chat/animals/Panda.png', FileGroup: 'Animals', Description: 'Panda', FileSize: 32},
{Filename: 'seahorse.png', FilePath: '../../assets/imgs/chat/animals/seahorse.png', FileGroup: 'Animals', Description: 'Seahorse', FileSize: 32},
{Filename: 't9batty_trans.png', FilePath: '../../assets/imgs/chat/animals/t9batty_trans.png', FileGroup: 'Animals', Description: 'Batty', FileSize: 32},
{Filename: 't9dog1_trans.png', FilePath: '../../assets/imgs/chat/animals/t9dog1_trans.png', FileGroup: 'Animals', Description: 'Doggy', FileSize: 32},
{Filename: 't9ducky_trans.png', FilePath: '../../assets/imgs/chat/animals/t9ducky_trans.png', FileGroup: 'Animals', Description: 'Duck', FileSize: 32},
{Filename: 't9elephant_trans.png', FilePath: '../../assets/imgs/chat/animals/t9elephant_trans.png', FileGroup: 'Animals', Description: 'Elephant', FileSize: 32},
{Filename: 't9foxy_trans.png', FilePath: '../../assets/imgs/chat/animals/t9foxy_trans.png', FileGroup: 'Animals', Description: 'Foxy', FileSize: 32},
{Filename: 't9froggy_trans.png', FilePath: '../../assets/imgs/chat/animals/t9froggy_trans.png', FileGroup: 'Animals', Description: 'Froggy', FileSize: 32},
{Filename: 't9kitty_trans.png', FilePath: '../../assets/imgs/chat/animals/t9kitty_trans.png', FileGroup: 'Animals', Description: 'Kitty', FileSize: 32},
{Filename: 't9lion_trans.png', FilePath: '../../assets/imgs/chat/animals/t9lion_trans.png', FileGroup: 'Animals', Description: 'Lion', FileSize: 32},
{Filename: 't9penguino_trans.png', FilePath: '../../assets/imgs/chat/animals/t9penguino_trans.png', FileGroup: 'Animals', Description: 'Penguin', FileSize: 32},
{Filename: 't9ratty_trans.png', FilePath: '../../assets/imgs/chat/animals/t9ratty_trans.png', FileGroup: 'Animals', Description: 'Ratty', FileSize: 32},
{Filename: 't9tuqui_trans.png', FilePath: '../../assets/imgs/chat/animals/t9tuqui_trans.png', FileGroup: 'Animals', Description: 'Tucan', FileSize: 32},
{Filename: 'teddy_bear_toy_1.png', FilePath: '../../assets/imgs/chat/animals/teddy_bear_toy_1.png', FileGroup: 'Animals', Description: 'Teddy Bear', FileSize: 32},
{Filename: 'teddy_bear_toy_3.png', FilePath: '../../assets/imgs/chat/animals/teddy_bear_toy_3.png', FileGroup: 'Animals', Description: 'Teddy Monkey', FileSize: 32},
{Filename: 'Turtle.png', FilePath: '../../assets/imgs/chat/animals/Turtle.png', FileGroup: 'Animals', Description: 'Turtle', FileSize: 32},
{Filename: 't9panda_trans.png', FilePath: '../../assets/imgs/chat/animals/t9panda_trans.png', FileGroup: 'Animals222,Panda2', FileSize: 32},
{Filename: 'fish.png', FilePath: '../../assets/imgs/chat/animals/fish.png', FileGroup: 'Animals', Description: 'Fish', FileSize: 32},
{Filename: 'Hippopotamus.png', FilePath: '../../assets/imgs/chat/animals/Hippopotamus.png', FileGroup: 'Animals', Description: 'Hippo', FileSize: 32},
{Filename: 'star.png', FilePath: '../../assets/imgs/chat/animals/star.png', FileGroup: 'Animals', Description: 'Star', FileSize: 32},
{Filename: 'coral.png', FilePath: '../../assets/imgs/chat/animals/coral.png', FileGroup: 'Animals', Description: 'Coral', FileSize: 32},
{Filename: 'cake_8.png', FilePath: '../../assets/imgs/chat/food/cake_8.png', FileGroup: 'Food', Description: 'Cake', FileSize: 32},
{Filename: 'cake_3.png', FilePath: '../../assets/imgs/chat/food/cake_3.png', FileGroup: 'Food', Description: 'Fruite Cake', FileSize: 32},
{Filename: 'cake_4.png', FilePath: '../../assets/imgs/chat/food/cake_4.png', FileGroup: 'Food', Description: 'Chease Cake', FileSize: 32},
{Filename: 'cake_7.png', FilePath: '../../assets/imgs/chat/food/cake_7.png', FileGroup: 'Food', Description: 'Tart Cake', FileSize: 32},
{Filename: 'cake.png', FilePath: '../../assets/imgs/chat/food/cake.png', FileGroup: 'Food', Description: 'Birthday Cake', FileSize: 32},
{Filename: 'cake_10.png', FilePath: '../../assets/imgs/chat/food/cake_10.png', FileGroup: 'Food', Description: 'Chocolate', FileSize: 32},
{Filename: 'cake_13.png', FilePath: '../../assets/imgs/chat/food/cake_13.png', FileGroup: 'Food', Description: 'Pease Of Cake', FileSize: 32},
{Filename: 'cake_14.png', FilePath: '../../assets/imgs/chat/food/cake_14.png', FileGroup: 'Food', Description: 'Rolling Cake', FileSize: 32},
{Filename: 'cake_15.png', FilePath: '../../assets/imgs/chat/food/cake_15.png', FileGroup: 'Food', Description: 'Cup Cake', FileSize: 32},
{Filename: 'pie.png', FilePath: '../../assets/imgs/chat/food/pie.png', FileGroup: 'Food', Description: 'Pie', FileSize: 32},
{Filename: 'cake_19.png', FilePath: '../../assets/imgs/chat/food/cake_19.png', FileGroup: 'Food', Description: 'Cherry Cake', FileSize: 32},
{Filename: 'cake_20.png', FilePath: '../../assets/imgs/chat/food/cake_20.png', FileGroup: 'Food', Description: 'Chocolate Cover', FileSize: 32},
{Filename: 'cake_choko.png', FilePath: '../../assets/imgs/chat/food/cake_choko.png', FileGroup: 'Food', Description: 'Chocolate Cake', FileSize: 32},
{Filename: 'cake2.png', FilePath: '../../assets/imgs/chat/food/cake2.png', FileGroup: 'Food', Description: 'Cherry Cover', FileSize: 32},
{Filename: 'muffin.png', FilePath: '../../assets/imgs/chat/food/muffin.png', FileGroup: 'Food', Description: 'Chocolate Muffin', FileSize: 32},
{Filename: 'cake_16.png', FilePath: '../../assets/imgs/chat/food/cake_16.png', FileGroup: 'Food', Description: 'Croissant', FileSize: 32},
{Filename: 'cream.png', FilePath: '../../assets/imgs/chat/food/cream.png', FileGroup: 'Food', Description: 'Cream', FileSize: 32},
{Filename: 'donuts2.png', FilePath: '../../assets/imgs/chat/food/donuts2.png', FileGroup: 'Food', Description: 'Donuts', FileSize: 32},
{Filename: 'donuts.png', FilePath: '../../assets/imgs/chat/food/donuts.png', FileGroup: 'Food', Description: 'Donuts For Two', FileSize: 32},
{Filename: 'hambruger.png', FilePath: '../../assets/imgs/chat/food/hambruger.png', FileGroup: 'Food', Description: 'Hambruger', FileSize: 32},
{Filename: 'cocktail.png', FilePath: '../../assets/imgs/chat/food/cocktail.png', FileGroup: 'Food', Description: 'Cocktail', FileSize: 32},
{Filename: 'coffee.png', FilePath: '../../assets/imgs/chat/food/coffee.png', FileGroup: 'Food', Description: 'Coffee', FileSize: 32},
{Filename: 'Coffee_by_Artdesigner_lv.png', FilePath: '../../assets/imgs/chat/food/Coffee_by_Artdesigner_lv.png', FileGroup: 'Food', Description: 'Latte', FileSize: 32},
{Filename: 'Ice.png', FilePath: '../../assets/imgs/chat/food/Ice.png', FileGroup: 'Food', Description: 'Ice', FileSize: 32},
{Filename: 'eh5.png', FilePath: '../../assets/imgs/chat/hearts/eh5.png', FileGroup: 'Hearts', Description: 'Hearth', FileSize: 32},
{Filename: 'em14.png', FilePath: '../../assets/imgs/chat/hearts/em14.png', FileGroup: 'Hearts', Description: 'Shiny Hearth', FileSize: 32},
{Filename: 'h1.png', FilePath: '../../assets/imgs/chat/hearts/h1.png', FileGroup: 'Hearts', Description: 'Cupido Heart', FileSize: 32},
{Filename: 'h2.png', FilePath: '../../assets/imgs/chat/hearts/h2.png', FileGroup: 'Hearts', Description: 'Broken Heart', FileSize: 32},
{Filename: 'h3.png', FilePath: '../../assets/imgs/chat/hearts/h3.png', FileGroup: 'Hearts', Description: 'Messed Up Heart', FileSize: 32},
{Filename: 'h4.png', FilePath: '../../assets/imgs/chat/hearts/h4.png', FileGroup: 'Hearts', Description: 'Be My Valentine', FileSize: 32},
{Filename: 'love_valentines_day_1.png', FilePath: '../../assets/imgs/chat/hearts/love_valentines_day_1.png', FileGroup: 'Hearts', Description: 'Gift Heart', FileSize: 32},
{Filename: 'love_valentines_day_2.png', FilePath: '../../assets/imgs/chat/hearts/love_valentines_day_2.png', FileGroup: 'Hearts', Description: 'Valentine Heart', FileSize: 32},
{Filename: 'love_valentines_day_4.png', FilePath: '../../assets/imgs/chat/hearts/love_valentines_day_4.png', FileGroup: 'Hearts', Description: 'Arrow Hearts', FileSize: 32},
{Filename: 'love_valentines_day_5.png', FilePath: '../../assets/imgs/chat/hearts/love_valentines_day_5.png', FileGroup: 'Hearts', Description: 'Marry Me', FileSize: 32},
{Filename: 'love_valentines_day_6.png', FilePath: '../../assets/imgs/chat/hearts/love_valentines_day_6.png', FileGroup: 'Hearts', Description: 'Baloon Heats', FileSize: 32},
{Filename: 'love_valentines_day_7.png', FilePath: '../../assets/imgs/chat/hearts/love_valentines_day_7.png', FileGroup: 'Hearts', Description: 'Sunny Heart', FileSize: 32},
{Filename: 'love_valentines_day_8.png', FilePath: '../../assets/imgs/chat/hearts/love_valentines_day_8.png', FileGroup: 'Hearts', Description: 'Star Heart', FileSize: 32},
{Filename: 'love_valentines_day_9.png', FilePath: '../../assets/imgs/chat/hearts/love_valentines_day_9.png', FileGroup: 'Hearts', Description: 'Taken Heart', FileSize: 32},
{Filename: 'love_valentines_day_10.png', FilePath: '../../assets/imgs/chat/hearts/love_valentines_day_10.png', FileGroup: 'Hearts', Description: 'Take My Heart', FileSize: 32},
{Filename: 'love_valentines_day_11.png', FilePath: '../../assets/imgs/chat/hearts/love_valentines_day_11.png', FileGroup: 'Hearts', Description: 'Our Hearts', FileSize: 32},
{Filename: 'love_valentines_day_12.png', FilePath: '../../assets/imgs/chat/hearts/love_valentines_day_12.png', FileGroup: 'Hearts', Description: 'Many Hearts', FileSize: 32},
{Filename: 'love_valentines_day_13.png', FilePath: '../../assets/imgs/chat/hearts/love_valentines_day_13.png', FileGroup: 'Hearts', Description: 'Free Heart', FileSize: 32},
{Filename: 'red_heart.png', FilePath: '../../assets/imgs/chat/hearts/red_heart.png', FileGroup: 'Hearts', Description: 'Flying Hearts', FileSize: 32},
{Filename: '14.png', FilePath: '../../assets/imgs/chat/objects/14.png', FileGroup: 'Objects', Description: 'Scale Of Justice', FileSize: 32},
{Filename: 'Hail_Heavy.png', FilePath: '../../assets/imgs/chat/weather/Hail_Heavy.png', FileGroup: 'Weather', Description: 'Heavy Rain', FileSize: 32},
{Filename: 'cake_1.png', FilePath: '../../assets/imgs/chat/season/cake_1.png', FileGroup: 'Season', Description: 'Christmas Candle', FileSize: 32},
{Filename: 'Bench_by_Artdesigner.lv.png', FilePath: '../../assets/imgs/chat/others/Bench_by_Artdesigner.lv.png', FileGroup: 'Others', Description: 'A Day At The Park', FileSize: 32}
];